title: <p align="center"> Tan See Ying </p>

logo: "images/SY.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/tan-see-ying-198466230/">LinkedIn</a> |
  <a href="https://github.com/seeying147">GitHub</a>
  </p>
  
  <p align="justify">
  Based in Singapore, I am a Mathematics graduate with a specialization in statistics at Nanyang Technological University. I had the privilege to intern as a Business Analyst at Advantest, with a focus on Robotic Processing Automation (RPA) and Process Mining projects.
  <br><br>
  My passion lies in exploring projects that blend mathematical rigour, statistical analysis and automation to solve real-world challenges.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
