title: <p align="center"> Tan See Ying </p>

logo: "images/SY.png?raw=true"

description:
  <p align="center">
  <a href="See Ying Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/tan-see-ying-198466230/">LinkedIn</a> |
  <a href="https://github.com/seeying147">GitHub</a>
  </p>
  
  <p align="justify">
  Based in Singapore, I am a Mathematics graduate specializing in Statistics at Nanyang Technological University. I had the privilege to intern as a Business Analyst at Advantest, focusing on Robotic Processing Automation (RPA) and Process Mining projects.
  <br><br>
  My passion lies in exploring projects that blend mathematical rigour, statistical analysis and automation to solve real-world challenges.
  <br><br>
  </p>


theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
